In [3]:
import numpy as np
from scipy.stats import uniform

In [ ]:
N = 1000000

tmp = np.arange(N)

data = (uniform.rvs(-1, 2, (N, 4)))**2
sum = np.sum(data, axis=1)

np.sum(sum<1)/N

np.float64(0.308593)

In [10]:
np.pi**2/2/2**4

0.30842513753404244

In [41]:
N = 4

data =  (uniform.rvs(-1, 2, (N, N, 4)))**2

mask = np.arange(N) > np.arange(N)[:, None]
data[mask] = 0

tmp = np.sum(data, axis=2)
print(tmp)
np.sum(tmp<1, axis=1)

[[1.64839711 0.         0.         0.        ]
 [1.90190693 0.89659359 0.         0.        ]
 [1.41371583 1.36611216 0.34234328 0.        ]
 [1.73646233 2.26674578 2.04487884 0.87976056]]


array([3, 3, 2, 1])

In [21]:
a = np.arange(4)
a>a[:, None]

array([[False,  True,  True,  True],
       [False, False,  True,  True],
       [False, False, False,  True],
       [False, False, False, False]])